INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (1,'YMML',0,'gate','Gate F 33','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (2,'YMML',1,'gate','Gate F 31','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (3,'YMML',2,'gate','Gate E 30','','VOZ',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (4,'YMML',3,'gate','Gate E 29','','VOZ',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (5,'YMML',4,'gate','Gate E 28','','VOZ',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (6,'YMML',5,'gate','Gate E 27','','VOZ',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (7,'YMML',6,'gate','Gate E 26','','VOZ',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (8,'YMML',7,'gate','Gate E 25','','VOZ',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (9,'YMML',8,'gate','Gate E 24','','VOZ',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (10,'YMML',9,'gate','Gate E 23','','VOZ',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (11,'YMML',10,'gate','Gate D 9','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (12,'YMML',11,'gate','Gate D 7','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (13,'YMML',12,'gate','Gate D 6','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (14,'YMML',13,'gate','Gate D 4','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (15,'YMML',14,'gate','Gate D 3','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (16,'YMML',15,'gate','Gate D 2','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (17,'YMML',16,'gate','Gate D 12','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (18,'YMML',17,'gate','Gate D','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (19,'YMML',18,'gate','Gate 22','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (20,'YMML',19,'gate','Gate 21','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (21,'YMML',20,'gate','Gate 20','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (22,'YMML',21,'gate','Gate 19','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (23,'YMML',22,'gate','Gate 18','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (24,'YMML',23,'gate','Gate 17','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (25,'YMML',24,'gate','Gate 16','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (26,'YMML',25,'gate','Gate 15','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (27,'YMML',26,'gate','Gate 14','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (28,'YMML',27,'gate','Gate 13','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (29,'YMML',28,'gate','Dock 31','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (30,'YMML',29,'gate','Dock 30','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (31,'YMML',30,'gate','Startup Location','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (32,'YMML',31,'gate','Startup Location','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (33,'YMML',32,'gate','Startup Location','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (34,'YMML',33,'gate','Startup Location','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (35,'YMML',34,'gate','Startup Location','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (36,'YMML',35,'gate','Startup Location','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (37,'YMML',36,'gate','Startup Location','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (38,'YMML',37,'gate','Startup Location','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (39,'YMML',38,'gate','Startup Location','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (40,'YMML',39,'gate','Startup Location','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (41,'YMML',40,'gate','Startup Location','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (42,'YMML',41,'gate','Startup Location','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (43,'YMML',42,'gate','Startup Location','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (44,'YMML',43,'gate','Startup Location','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (45,'YMML',44,'gate','Startup Location','','QFA',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (46,'YMML',45,'gate','Startup Location','','VOZ',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (47,'YMML',46,'gate','Startup Location','','VOZ',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (48,'YMML',47,'gate','Startup Location','','VOZ',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (49,'YMML',48,'gate','Startup Location','','VOZ',1);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (50,'YMML',49,'gate','Startup Location','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (51,'YMML',50,'gate','Startup Location','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (52,'YMML',51,'gate','Startup Location','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (53,'YMML',52,'gate','Startup Location','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (54,'YMML',53,'gate','Startup Location','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (55,'YMML',54,'gate','Startup Location','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (56,'YMML',55,'gate','Startup Location','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (57,'YMML',56,'gate','Startup Location','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (58,'YMML',57,'gate','Startup Location','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (59,'YMML',58,'gate','Startup Location','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (60,'YMML',59,'gate','Startup Location','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (61,'YMML',60,'gate','Startup Location','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (62,'YMML',61,'gate','Startup Location','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (63,'YMML',62,'gate','Startup Location','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (64,'YMML',63,'gate','Startup Location','','',0);
INSERT INTO "parking" ("id","airport_code","index","type","name","number","airline_codes","has_airline_codes") VALUES (65,'YMML',64,'gate','Startup Location','','',0);
