# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fgo\ui\ConfigureAgentPaths.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConfigureAgentPathsDialog(object):
    def setupUi(self, ConfigureAgentPathsDialog):
        ConfigureAgentPathsDialog.setObjectName("ConfigureAgentPathsDialog")
        ConfigureAgentPathsDialog.resize(594, 286)
        self.verticalLayout = QtWidgets.QVBoxLayout(ConfigureAgentPathsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(ConfigureAgentPathsDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.leFGRoot = QtWidgets.QLineEdit(self.frame)
        self.leFGRoot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.leFGRoot.setReadOnly(True)
        self.leFGRoot.setObjectName("leFGRoot")
        self.gridLayout.addWidget(self.leFGRoot, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.leFgfsExec = QtWidgets.QLineEdit(self.frame)
        self.leFgfsExec.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.leFgfsExec.setReadOnly(True)
        self.leFgfsExec.setObjectName("leFgfsExec")
        self.gridLayout.addWidget(self.leFgfsExec, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.leFGHome = QtWidgets.QLineEdit(self.frame)
        self.leFGHome.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.leFGHome.setReadOnly(True)
        self.leFGHome.setObjectName("leFGHome")
        self.gridLayout.addWidget(self.leFGHome, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.leAircraft = QtWidgets.QLineEdit(self.frame)
        self.leAircraft.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.leAircraft.setReadOnly(True)
        self.leAircraft.setObjectName("leAircraft")
        self.gridLayout.addWidget(self.leAircraft, 5, 1, 1, 1)
        self.leTSPath = QtWidgets.QLineEdit(self.frame)
        self.leTSPath.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.leTSPath.setReadOnly(True)
        self.leTSPath.setObjectName("leTSPath")
        self.gridLayout.addWidget(self.leTSPath, 4, 1, 1, 1)
        self.labelFGHome = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelFGHome.setFont(font)
        self.labelFGHome.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelFGHome.setOpenExternalLinks(True)
        self.labelFGHome.setObjectName("labelFGHome")
        self.gridLayout.addWidget(self.labelFGHome, 3, 3, 1, 1)
        self.labelFGRoot = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.labelFGRoot.setFont(font)
        self.labelFGRoot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.labelFGRoot.setOpenExternalLinks(True)
        self.labelFGRoot.setObjectName("labelFGRoot")
        self.gridLayout.addWidget(self.labelFGRoot, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.pbFGRoot = QtWidgets.QPushButton(self.frame)
        self.pbFGRoot.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/common/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pbFGRoot.setIcon(icon)
        self.pbFGRoot.setObjectName("pbFGRoot")
        self.gridLayout.addWidget(self.pbFGRoot, 1, 2, 1, 1)
        self.pbFGExec = QtWidgets.QPushButton(self.frame)
        self.pbFGExec.setText("")
        self.pbFGExec.setIcon(icon)
        self.pbFGExec.setObjectName("pbFGExec")
        self.gridLayout.addWidget(self.pbFGExec, 0, 2, 1, 1)
        self.pbFGHome = QtWidgets.QPushButton(self.frame)
        self.pbFGHome.setText("")
        self.pbFGHome.setIcon(icon)
        self.pbFGHome.setObjectName("pbFGHome")
        self.gridLayout.addWidget(self.pbFGHome, 3, 2, 1, 1)
        self.pbTS = QtWidgets.QPushButton(self.frame)
        self.pbTS.setText("")
        self.pbTS.setIcon(icon)
        self.pbTS.setObjectName("pbTS")
        self.gridLayout.addWidget(self.pbTS, 4, 2, 1, 1)
        self.pbAircraft = QtWidgets.QPushButton(self.frame)
        self.pbAircraft.setText("")
        self.pbAircraft.setIcon(icon)
        self.pbAircraft.setObjectName("pbAircraft")
        self.gridLayout.addWidget(self.pbAircraft, 5, 2, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConfigureAgentPathsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ConfigureAgentPathsDialog)
        self.buttonBox.accepted.connect(ConfigureAgentPathsDialog.accept)
        self.buttonBox.rejected.connect(ConfigureAgentPathsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConfigureAgentPathsDialog)

    def retranslateUi(self, ConfigureAgentPathsDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfigureAgentPathsDialog.setWindowTitle(_translate("ConfigureAgentPathsDialog", "Configure Agent Paths"))
        self.label_2.setText(_translate("ConfigureAgentPathsDialog", "FGRoot Path:"))
        self.label_4.setText(_translate("ConfigureAgentPathsDialog", "TerraSync Path:"))
        self.label.setText(_translate("ConfigureAgentPathsDialog", "FlightGear Executable Path:"))
        self.labelFGHome.setText(_translate("ConfigureAgentPathsDialog", "<a href=\"http://wiki.flightgear.org/$FG_HOME\">Where user specific<br>\n"
"data is stored.</a>"))
        self.labelFGRoot.setText(_translate("ConfigureAgentPathsDialog", "<a href=\"http://wiki.flightgear.org/$FG_ROOT\">Main data directory.</a>"))
        self.label_3.setText(_translate("ConfigureAgentPathsDialog", "FGHome Path:"))
        self.label_5.setText(_translate("ConfigureAgentPathsDialog", "Aircraft Path:"))

import resources_rc
