# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fgo/ui/CustomSettingsDialog.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CustomSettingsDialog(object):
    def setupUi(self, CustomSettingsDialog):
        CustomSettingsDialog.setObjectName("CustomSettingsDialog")
        CustomSettingsDialog.resize(400, 564)
        self.verticalLayout = QtWidgets.QVBoxLayout(CustomSettingsDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(CustomSettingsDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cbDisablePanel = QtWidgets.QCheckBox(self.frame)
        self.cbDisablePanel.setObjectName("cbDisablePanel")
        self.verticalLayout_2.addWidget(self.cbDisablePanel)
        self.cbDisableHUD = QtWidgets.QCheckBox(self.frame)
        self.cbDisableHUD.setObjectName("cbDisableHUD")
        self.verticalLayout_2.addWidget(self.cbDisableHUD)
        self.cbDisableAntiAliasHUD = QtWidgets.QCheckBox(self.frame)
        self.cbDisableAntiAliasHUD.setObjectName("cbDisableAntiAliasHUD")
        self.verticalLayout_2.addWidget(self.cbDisableAntiAliasHUD)
        self.cbEnableClouds = QtWidgets.QCheckBox(self.frame)
        self.cbEnableClouds.setObjectName("cbEnableClouds")
        self.verticalLayout_2.addWidget(self.cbEnableClouds)
        self.cbEnableClouds3D = QtWidgets.QCheckBox(self.frame)
        self.cbEnableClouds3D.setObjectName("cbEnableClouds3D")
        self.verticalLayout_2.addWidget(self.cbEnableClouds3D)
        self.cbEnableFullscreen = QtWidgets.QCheckBox(self.frame)
        self.cbEnableFullscreen.setObjectName("cbEnableFullscreen")
        self.verticalLayout_2.addWidget(self.cbEnableFullscreen)
        self.cbEnableTerraSync = QtWidgets.QCheckBox(self.frame)
        self.cbEnableTerraSync.setObjectName("cbEnableTerraSync")
        self.verticalLayout_2.addWidget(self.cbEnableTerraSync)
        self.cbEnableRealWeatherFetch = QtWidgets.QCheckBox(self.frame)
        self.cbEnableRealWeatherFetch.setObjectName("cbEnableRealWeatherFetch")
        self.verticalLayout_2.addWidget(self.cbEnableRealWeatherFetch)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(CustomSettingsDialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.leFOV = QtWidgets.QLineEdit(self.frame_2)
        self.leFOV.setObjectName("leFOV")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leFOV)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.leViewOffset = QtWidgets.QLineEdit(self.frame_2)
        self.leViewOffset.setPlaceholderText("")
        self.leViewOffset.setObjectName("leViewOffset")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leViewOffset)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(CustomSettingsDialog)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.lwAdditionalArgs = QtWidgets.QListWidget(self.frame_3)
        self.lwAdditionalArgs.setObjectName("lwAdditionalArgs")
        self.verticalLayout_3.addWidget(self.lwAdditionalArgs)
        self.frame_4 = QtWidgets.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbAddCustomArg = QtWidgets.QPushButton(self.frame_4)
        self.pbAddCustomArg.setObjectName("pbAddCustomArg")
        self.horizontalLayout.addWidget(self.pbAddCustomArg)
        self.pbRemoveCustomArg = QtWidgets.QPushButton(self.frame_4)
        self.pbRemoveCustomArg.setObjectName("pbRemoveCustomArg")
        self.horizontalLayout.addWidget(self.pbRemoveCustomArg)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.verticalLayout.addWidget(self.frame_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(CustomSettingsDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(CustomSettingsDialog)
        self.buttonBox.accepted.connect(CustomSettingsDialog.accept)
        self.buttonBox.rejected.connect(CustomSettingsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CustomSettingsDialog)

    def retranslateUi(self, CustomSettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        CustomSettingsDialog.setWindowTitle(_translate("CustomSettingsDialog", "Agent Custom Settings"))
        self.cbDisablePanel.setText(_translate("CustomSettingsDialog", "Disable Panel"))
        self.cbDisableHUD.setText(_translate("CustomSettingsDialog", "Disable HUD"))
        self.cbDisableAntiAliasHUD.setText(_translate("CustomSettingsDialog", "Disable Anti-Alias HUD"))
        self.cbEnableClouds.setText(_translate("CustomSettingsDialog", "Enable Clouds"))
        self.cbEnableClouds3D.setText(_translate("CustomSettingsDialog", "Enable Clouds 3D"))
        self.cbEnableFullscreen.setText(_translate("CustomSettingsDialog", "Enable Fullscreen"))
        self.cbEnableTerraSync.setText(_translate("CustomSettingsDialog", "Enable Terra Sync"))
        self.cbEnableRealWeatherFetch.setText(_translate("CustomSettingsDialog", "Enable Real Weather Fetch"))
        self.label.setText(_translate("CustomSettingsDialog", "Field of View:"))
        self.label_2.setText(_translate("CustomSettingsDialog", "View Offset:"))
        self.leViewOffset.setToolTip(_translate("CustomSettingsDialog", "Specify the default forward view direction in degrees. Increments of 50-60 degrees are suggested."))
        self.label_3.setText(_translate("CustomSettingsDialog", "Additional Args:"))
        self.pbAddCustomArg.setText(_translate("CustomSettingsDialog", "Add"))
        self.pbRemoveCustomArg.setText(_translate("CustomSettingsDialog", "Remove"))


